config/routes.rb
Barcampgb::Application.routes.draw do
  # resources
  resources :users, :sessions, :password_resets

  get "/scheduler/people" => "scheduler#people"
  get "/scheduler/sessions" => "scheduler#sessions"

  resources :presentations do
    get 'attend', on: :member
    get 'unattend', on: :member
  end

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end

  # pages
  get 'about' => 'pages#about'
  get 'code-of-conduct' => 'pages#coc'

  # custom routes
  get 'signin' => 'sessions#new'
  get 'signout' => 'sessions#destroy'

  root to: 'pages#home'
end

app/models/presentation.rb
class Presentation < ActiveRecord::Base
  belongs_to :presenter, class_name: 'User', foreign_key: 'user_id'
  has_and_belongs_to_many :users

  validates :title, presence: true, length: { maximum: 200, minimum: 6 }
  validates :description, presence: true, length: { maximum: 2000, minimum: 50 }

  def self.all_with_users
    @presentations ||= Presentation.includes(:users).load
    @presentations
  end

  def non_conflicting_presentations
    Presentation.all_with_users.select{|p| (p.users & self.users).empty?}
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password(validations: false)

  has_one :presentation
  has_and_belongs_to_many :presentations

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true,
                    uniqueness: true,
                    format: { with: /\A[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]+\z/ }
  validates :shirt_size, presence: true

  after_create :send_registration_email

  def full_name
    "#{first_name} #{last_name}"
  end

  def short_name
    "#{first_name} #{last_name.first}"
  end

  def send_password_reset
    set_password_reset_token
    UserMailer.password_reset_email(self).deliver
  end

  def attend(presentation)
    presentations << presentation unless is_attending?(presentation)
  end

  def unattend(presentation)
    presentations.delete(presentation) if is_attending?(presentation)
  end

  def is_attending?(presentation)
    presentations.include?(presentation)
  end

  def is_admin?
    admin?
  end

  private

  def send_registration_email
    set_password_reset_token
    UserMailer.registration_email(self).deliver
  end

  def set_password_reset_token
    generate_token(:password_reset_token)
    self.password_reset_sent_at = Time.zone.now
    save!
  end

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while User.exists?(column => self[column])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  # what happens when a user isn't logged in - might want to do something besides redirect home
  def login!
    redirect_to new_session_path unless current_user
  end

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def signed_in?
    !current_user.nil?
  end
  helper_method :signed_in?
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
  
  def coc
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    user.send_password_reset if user
    redirect_to root_url
    flash[:success] = 'Email sent with password reset instructions.'
  end

  def edit
    @user = User.find_by(password_reset_token: params[:id])

    redirect_to root_path unless @user
  end

  def update
    @user = User.find_by(password_reset_token: params[:id])

    if @user.update_attributes(user_params)
      redirect_to new_session_path
      flash[:success] = 'Password has been reset.'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :login!, except: [:index]
  before_action :get_presentation, only: [:edit, :update, :attend, :unattend]
  before_action :authorize_presentation, only: [:edit, :update]

  def index
    @presentations = Presentation.order("RANDOM()")
  end

  def new
    @presentation = Presentation.new
  end

  def create
    @presentation = Presentation.new(presentation_params)
    @presentation.presenter = current_user

    if @presentation.save
      @presentations = Presentation.all.order('created_at DESC')
      render :success
    else
      render :error
    end
  end

  def edit
  end

  def update
    if @presentation.update_attributes(presentation_params)
      flash[:success] = 'Presentation updated successfully!'
      redirect_to presentations_path
    else
      render :edit
    end
  end

  def attend
    current_user.attend(@presentation)
  end

  def unattend
    current_user.unattend(@presentation)
    render :attend
  end

  private

  def presentation_params
    params.require(:presentation).permit(:title, :description)
  end

  def get_presentation
    @presentation = Presentation.find(params[:id])
  end

  def authorize_presentation
    raise ActiveRecord::RecordNotFound unless @presentation.presenter == current_user
  end
end

app/controllers/scheduler_controller.rb
class SchedulerController < ApplicationController
  def people
    raise ActionController::RoutingError.new('Not Found') unless current_user.is_admin?

    @presentations = Presentation.includes(:users).load.reject{|p| p.users.empty?}.sort_by{|p| p.users.size}.reverse
    @users = User.includes(:presentations).reject{|u| u.presentations.empty?}.sort_by{|u| u.presentations.size}.reverse
  end

  def sessions
    raise ActionController::RoutingError.new('Not Found') unless current_user.is_admin?

    @presentations = Presentation.includes(:users).load.sort{|p| p.users.size}.reverse
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to presentations_path if signed_in?
  end

  def create
    user = User.find_by(email: params[:email])

    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "You're in!"
      redirect_to presentations_path
    else
      flash[:error] = "Sorry, we couldn't find you in our system."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You're logged out!"
    redirect_to presentations_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      render :success
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(
      :first_name,
      :last_name,
      :email,
      :twitter,
      :shirt_size,
      :diet_concerns
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_block_about.html.erb
<div class="block block-about">
  <div class="container">
    <a id="about" class="anchor"></a>
    <h2 class="block-title">What is BarCamp?</h2>
      <p class="lead alert alert-warning text-center">
        <a href="" data-toggle="modal" data-target="#registration-form">Register now</a> for BarCamp Green Bay 2014 and join <strong><%= User.count %></strong> other campers!
      </p>
      <p>This free event is entirely produced by <strong>you</strong>, the participants, so chances are if you are an attendee you are also a speaker. The topics tend to be somewhat tech-focused, but anyone and everyone is welcome and encouraged to attend and present on whatever they find fascinating.</p>
      <p>Check out <a href="https://plus.google.com/photos/+ChrisJaure/albums/5947313045468361489" target="_blank">photos from BarCamp Green Bay 2013</a>! If you have any questions, feel free to <a href="mailto:info@barcampgb.org">send an email</a>.</p>
      <div class="row-fluid">
        <div class="span4">
          <h3>How does it work?</h3>
          <p>A typical BarCamp starts off with participant collaboration on <a href="https://plus.google.com/photos/+ChrisJaure/albums/5947313045468361489/5947314505322668098?pid=5947314505322668098&oid=106571931916635496454" target="_blank">the session grid</a>, which is broken up into 45-minute blocks. Propose a talk, discussion, demo, workshop… whatever works for you!</p>
        </div>
        <div class="span4">
          <h3>Give a talk? Really?</h3>
          <p>Hey, if presenting isn’t your thing, that's cool. We understand, but we ask that you find another way to contribute, like helping with set-up or keeping the conference area tidy.</p>
        </div>
        <div class="span4">
          <h3>What about topics?</h3>
          <p>Here are some ideas from past events: 3d printing, hacker/makerspaces, survival, Minecraft, retro gaming, AI, emotional intelligence, and web development.</p>
        </div>
      </div>
      <div class="row-fluid">
        <div class="span4">
          <h3>Code of Conduct</h3>
          <p>BarCamp Green Bay is dedicated to a harassment-free conference experience for everyone. Please read our <%= link_to('code of conduct', 'code-of-conduct') %>.</p>
        </div>
        <div class="span4">
          <h3>KidsCamp</h3>
          <p>This year we'll be organizing a <strong>KidsCamp</strong> with fun things for children to do so bring yours along and encourage them to present too!</p>
        </div>
        <div class="span4">
          <h3>Nodeschool Wisconsin</h3>
          <p>Come for Nodeschool Wisconsin's first event and learn you some node! For more information, check out <a href="http://nodeschool.io/">nodeschool.io</a> and <a href="http://nodeschool.io/wisconsin/">Nodeschool Wisconsin</a>.</p>
        </div>
      </div>
  </div>
</div>

app/views/application/_block_intro.html.erb
<div class="block-intro stretch-mobile">
  <div class="container">
    <%= image_tag('logo-white.png', class: 'logo') %>
    <p class="lead"><strong>BarCamp Green Bay</strong> is part of an international network of community-organized, participant-led conferences that create diverse and open environments for sharing knowledge.</p>
  </div>
</div>

app/views/application/_block_location.html.erb
<div class="block block-location stretch-mobile">
  <div class="container">
    <div class="row-fluid">
      <div class="span5 offset1">
        <div class="calendar block-icon">
          <div class="calendar-month">Nov</div>
          <div class="calendar-day">1</div>
        </div>
        <h3>Saturday</h3>
        <p>November 1, 2014</p>
      </div>
      <div class="span6">
        <%= image_tag('location-marker.png', class: 'block-icon location-marker') %>
        <h3 class="clear-sp-outer-top">
          NWTC Corporate Conference Center
          <a href="https://www.google.com/maps/place/NWTC+Corporate+Conference+Center/@44.527327,-88.107321,17z/data=!3m1!4b1!4m2!3m1!1s0x8802f9e7ab077a8f:0x7861e0117a83b803" title="Get directions" target="_blank">
            ➪
          </a>
        </h3>
        <p>
          2740 W Mason St<br />
          Green Bay, WI<br />
        </p>
      </div>
    </div>
  </div>
</div>

app/views/application/_block_register.html.erb
<div id="registration-form" class="modal hide fade" tabindex="-1" role="dialog" aria-hidden="true">
  <%= render 'users/fields', user: User.new %>
</div>

app/views/application/_block_schedule.html.erb
<div class="block block-schedule stretch-mobile">
  <div class="container">
    <a id="schedule" class="anchor"></a>
    <h2 class="block-title">Schedule</h2>
    <div class="row-fluid">
      <div class="span10 offset1">
        <div class="event-time-bg"></div>
        <!-- <div class="event">
          <div class="event-time">
            8:00 <small>a.m.</small>
          </div>
          <div class="event-info">
            <h3 class="event-info-title">Breakfast</h3>
            <div class="event-info-description">
              Sponsored by <a href="http://github.com/" target="_blank">GitHub</a> and <a href="http://sparknet.jobs/" target="_blank">SparkNET</a>
            </div>
          </div>
        </div> -->
        <div class="event">
          <div class="event-time">
            9:00 <small>a.m.</small>
          </div>
          <div class="event-info">
            <h3 class="event-info-title">Opening Session</h3>
          </div>
        </div>
        <div class="event">
          <div class="event-time">
            10:00 <small>a.m.</small>
          </div>
          <div class="event-info">
            <h3 class="event-info-title">Breakout Sessions</h3>
          </div>
        </div>
        <div class="event">
          <div class="event-time">
            12:00 <small>p.m.</small>
          </div>
          <div class="event-info">
            <h3 class="event-info-title">Lunch catered by Gallagher's Pizza</h3>
            <div class="event-info-description">
              Sponsored by <a href="http://gallagherspizza.com/" target="_blank">Gallagher's Pizza</a> and <a href="http://greenbay.startupweekend.org/" target="_blank">Startup Weekend Green Bay</a>
            </div>
          </div>
        </div>
        <div class="event">
          <div class="event-time">
            1:00 <small>p.m.</small>
          </div>
          <div class="event-info">
            <h3 class="event-info-title">Breakout Sessions</h3>
          </div>
        </div>
        <div class="event">
          <div class="event-time">
            4:00 <small>p.m.</small>
          </div>
          <div class="event-info">
            <h3 class="event-info-title">Closing Session</h3>
          </div>
        </div>
        <div class="event">
          <div class="event-time">
            5:00 <small>p.m.</small>
          </div>
          <div class="event-info">
            <h3 class="event-info-title">Dinner (not provided)</h3>
            <div class="event-info-description">small groups at local restaurants</div>
          </div>
        </div>
        <div class="event">
          <div class="event-time">
            7:00 <small>p.m.</small>
          </div>
          <div class="event-info">
            <h3 class="event-info-title">Unstructured</h3>
            <div class="event-info-description">play games, hack on some code, or just mingle!</div>
          </div>
        </div>
        <div class="event">
          <div class="event-time">
            11:30 <small>p.m.</small>
          </div>
          <div class="event-info">
            <h3 class="event-info-title">Clean-Up</h3>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_block_sponsors.html.erb
<div class="block block-sponsors">
  <div class="container">
    <a id="sponsor" class="anchor"></a>
    <h2 class="block-title">Sponsors</h2>
    <div class="row-fluid">
      <div class="span8">
        <ul class="thumbnails">
          <li>
            <a class="thumbnail" href="http://www.nwtc.edu/" target="_blank" title="Northeast Wisconsin Technical College"><%= image_tag('NWTC-logo.gif', alt: 'Northeast Wisconsin Technical College') %></a>
          </li>
          <li>
            <a class="thumbnail" href="http://greenbay.startupweekend.org/" target="_blank" title="Startup Weekend Green Bay"><%= image_tag('swgb-logo.png', alt: 'Startup Weekend Green Bay') %></a>
          </li>
          <li>
            <a class="thumbnail" href="http://gallagherspizza.com/" target="_blank" title="Gallagher's Pizza"><%= image_tag('gallaghers-logo.png', alt: 'Gallagher\'s Pizza') %></a>
          </li>
          <li>
            <a class="thumbnail" href="http://smartsocialmedia.com/" target="_blank" title="Smart Social Media"><%= image_tag('Smart-Social-Media-logo.png', alt: 'Smart Social Media', width: 200) %></a>
          </li>
          <li>
            <a class="thumbnail" href="http://www.mxmegastore.com/" target="_blank" title="MxMegastore"><%= image_tag('mxmegastore-logo.jpg', alt: 'MxMegastore') %></a>
          </li>
        </ul>
      </div>
      <div class="span4">
        <p class="lead"></p>
      </div>
    </div>
    <hr />
    <p>Be part of something amazing. <a href="https://www.payitsquare.com/collect-page/43084" target="_blank">Sponsor BarCamp Green Bay!</a></p>
    <p>Consider sponsoring $50-$200 and we will list you on this site and give you a shout-out during the event.</p>
  </div>
</div>

app/views/application/_header.html.erb
<div class="header navbar" role="navigation">
  <div class="navbar-inner">
    <div class="container clearfix">
      <%= link_to('BarCamp Green Bay', root_path, class: 'hidden-desktop home-link') %>
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>

      <div class="nav-collapse collapse">
        <div class="pull-left">
          <% if current_page?(root_url) %>
            <a href="/#about">About</a>
            <a href="/#schedule">Schedule</a>
            <%= link_to('Sessions', presentations_path) %>
          <% else %>
            <%= link_to('Home', root_path) %>
            <% if signed_in? %>
              <%= link_to('Sign out', signout_path) %>
            <% else %>
              <%= link_to('Sign in', signin_path) %>
            <% end %>
          <% end %>
        </div>
        <div class="pull-right">
          <a href="https://twitter.com/BarCampGB" title="@BarCampGB">
            <%= image_tag('twitter-bird-dark-bgs.png') %>
          </a>
          <a class="btn-cta" href="" data-toggle="modal" data-target="#registration-form" title="Join <%= User.count %> other campers!">Register</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/application/_main_nav.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="navbar-inner">
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>

    <%= link_to('BarCamp Green Bay', root_path, class: 'brand') %>

    <div class="collapse nav-collapse collapse">
      <ul class="nav">
        <li<%= ' class="active"' if current_page?(controller: 'pages', action: 'home') %>><%= link_to('Home', root_path) %></li>
        <li<%= ' class="active"' if current_page?(controller: 'pages', action: 'about') %>><%= link_to('About', about_path) %></li>
        <li<%= ' class="active"' if current_page?(controller: 'pages', action: 'donate') %>><%= link_to('Donate', donate_path) %></li>
        <li<%= ' class="active"' if current_page?(controller: 'users', action: 'new') %>><%= link_to('Register', new_user_path) %></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/application/_messages.html.erb
<% flash.each do |type, message| %>
  <div class="alert alert-<%= type %> alert-block fade in flash-message">
    <a class="close" data-dismiss="alert" href="#">&times;</a>
    <p><%= message %></p>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarCamp Green Bay</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="<%= image_url('favicon.ico') %>">
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= csrf_meta_tags %>
  </head>
  <body class="<%= body_class %>">
    <%= render 'header' %>
    <%= render 'messages' %>

    <%= yield %>

    <%= render 'block_register' %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About Us!</h1>

app/views/pages/coc.html.erb
<div class="block stretch-mobile">
    <div class="container text-container">
        <h2 class="block-title">Code of Conduct</h2>
        <p>BarCamp Green Bay is dedicated to providing a harassment-free conference experience for everyone, regardless of gender, gender identity and expression, sexual orientation, disability, physical appearance, body size, race, age or religion. We do not tolerate harassment of conference participants in any form. Conference participants violating these rules may be sanctioned or expelled from the conference at the discretion of the conference organizers.</p>
        <p>Harassment includes verbal comments that reinforce social structures of domination, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention. Participants asked to stop any harassing behavior are expected to comply immediately.</p>
        <p>If a participant engages in harassing behavior, the conference organizers may take any action they deem appropriate, including warning the offender or expulsion from the conference. If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact a member of conference staff immediately.</p>
        <p>Conference staff will be happy to help participants contact venue security or local law enforcement, provide escorts, or otherwise assist those experiencing harassment to feel safe for the duration of the conference. We value your attendance.</p>
        <p>We expect participants to follow these rules at all conference venues and conference-related social events.</p>
        <h3>Contact Information:</h3>
        <ul>
            <li>Organizer Email: <a href="mailto:info@barcampgb.org">info@barcampgb.org</a></li>
            <li>Organizer Phone Number: 920-403-0630</li>
            <li>Twitter Handle: <a href="https://twitter.com/BarCampGB">@BarCampGB</a></li>
        </ul>
    </div>
</div>

app/views/pages/donate.html.erb
<h1>Donate!</h1>

app/views/pages/home.html.erb
<%= render 'block_intro' %>
<%= render 'block_location' %>
<%= render 'block_about' %>
<%= render 'block_schedule' %>
<%= render 'block_sponsors' %>

app/views/password_resets/edit.html.erb
<div class="row-fluid">
  <div class="span4 offset4">
    <%= form_for(@user, url: password_reset_path(params[:id]), html: { class: 'single-form' }) do |f| %>
      <h1>Set Your Password</h1>

      <% if @user.errors.any? %>
        <div class="error_messages">
          <h2>Form is invalid</h2>
          <ul>
            <% for message in @user.errors.full_messages %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="field">
        <%= f.label(:password) %>
        <%= f.password_field(:password, class: 'input-block-level') %>
      </div>
      <div class="field">
        <%= f.label(:password_confirmation) %>
        <%= f.password_field(:password_confirmation, class: 'input-block-level') %>
      </div>

      <%= f.submit('Update Password', class: 'btn btn-primary') %>
    <% end %>
  </div>
</div>

app/views/password_resets/new.html.erb
<div class="row-fluid">
  <div class="span4 offset4">
    <%= form_tag(password_resets_path, method: :post, class: 'single-form') do %>
      <h1>Reset Your Password</h1>
      <p>Enter your email address and we will send you an email with information on how to reset your password.</p>
      <div class="field">
        <%= label_tag(:email) %>
        <%= text_field_tag(:email, params[:email], class: 'input-block-level') %>
      </div>
      <%= submit_tag('Reset Password', class: 'btn btn-primary') %>
    <% end %>
  </div>
</div>

app/views/presentations/_attendance.html.erb
<div class="attendance-info">
  <% if signed_in? %>
    <% if current_user.presentations.include?(presentation) %>
      <%= link_to('Unattend This Session', unattend_presentation_path(presentation), remote: true, class: 'btn btn-danger toggle-attendance') %>
    <% else %>
      <%= link_to('Attend This Session', attend_presentation_path(presentation), remote: true, class: 'btn btn-primary toggle-attendance') %>
    <% end %>
  <% end %>
  <span class="attendance-count"><%= pluralize(presentation.users.count, 'attendee') %></span>
  <% if not signed_in? %>
  	<%= link_to('Sign in to attend', signin_path) %>
  <% end %>
</div>

app/views/presentations/_fields.html.erb
<% presentation = @presentation.present? ? @presentation : Presentation.new %>
<%= simple_form_for(presentation, url: presentations_path, remote: true, html: { class: 'modal hide fade', id: 'presentation-modal' }) do |f| %>
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h3>Submit Your Session</h3>
  </div>
  <div class="modal-body">
      <%= f.input(:title, input_html: { class: 'input-block-level' }) %>
      <%= f.input(:description, input_html: { class: 'input-block-level', rows: 5 }) %>
  </div>
  <div class="modal-footer">
    <a class="inline" data-dismiss="modal" href="#">Close</a>
    <%= f.button(:submit, 'Submit', class: 'btn btn-primary btn-large') %>
  </div>
<% end %>

app/views/presentations/attend.js.erb
$('.presentation-<%= @presentation.id %>')
  .find('.attendance-info')
  .html("<%= j(render 'presentations/attendance', presentation: @presentation) %>");

app/views/presentations/edit.html.erb
<div class="row-fluid">
  <div class="span6 offset3">
    <div class="box">
      <h2>Edit Session</h2>
      <%= simple_form_for(@presentation, html: { style: 'margin-bottom: 0;' }) do |f| %>
        <%= f.input(:title, input_html: { class: 'input-block-level' }) %>
        <%= f.input(:description, input_html: { class: 'input-block-level', rows: 5 }) %>
        <div class="clearfix">
          <%= f.button(:submit, 'Update Presentation', class: 'btn btn-primary btn-large pull-right') %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/presentations/error.js.erb
$('#presentation-modal').html("<%= j(render 'presentations/fields', presentation: @presentation) %>");

app/views/presentations/index.html.erb
<div class="container presentations">
  <%= link_to('Submit Your Session', '', class: 'btn btn-large btn-success pull-right', data: { target: '#presentation-modal', toggle: 'modal' }) %>
  <h1>Session Proposals</h1>
  <div class="alert alert-info">
    Remember these are just proposals! The real session schedule will be created the day of the event.
  </div>
  <% if @presentations.any? %>
    <% @presentations.each do |presentation| %>
      <div class="box presentation presentation-<%= presentation.id %>">
        <%= link_to('Edit Your Presentation', edit_presentation_path(presentation), class: 'btn btn-primary btn-small pull-right') if presentation.presenter == current_user %>
        <h2><%= presentation.title %></h2>
        <h4 class="presentation-presenter">By: <%= presentation.presenter.full_name %></h4>
        <%= simple_format(presentation.description) %>
        <%= render 'attendance', presentation: presentation %>
      </div>
    <% end %>
  <% else %>
    <div class="box">
      <p>We don't have any sessions yet... Perhaps you should <%= link_to('create the first one', '', data: { target: '#presentation-modal', toggle: 'modal' }) %>.</p>
    </div>
  <% end %>
</div>


<% if signed_in? %>
  <%= render 'presentations/fields' %>
<% else %>
  <%= render 'sessions/modal' %>
<% end %>

app/views/presentations/new.html.erb
<div class="row-fluid">
  <div class="span6 offset3">
    <div class="box">
      <%= render 'fields' %>
    </div>
  </div>
</div>

app/views/presentations/success.js.erb
$('#presentation-modal').find('.modal-body').html('<div class="alert alert-success">Session submitted successfully!</div>')

$('#presentation-modal').find('.modal-footer').remove();

$('#presentation-modal').delay(2000).modal('hide');

$('.container.presentations').replaceWith("<%= j(render template: 'presentations/index') %>");

app/views/scheduler/index.html.erb
<div class="container presentations">
  <h1>Scheduler</h1>
  <div class="row-fluid">
    <div class="span12" style="overflow-x: scroll;">
      <table class="table table-striped">
        <tr>
          <th>Presentation Name</th>
          <% @users.each do |user| %>
            <th title="<%= user.full_name %>"><%= user.short_name %> (<%= user.presentations.count %>)</th>
          <% end %>
        </tr>
        <% @presentations.each do |presentation| %>
          <tr>
            <td title="<%= presentation.non_conflicting_presentations.collect{|p| p.title}.join("\n") %>"><%= presentation.title %> (<%= presentation.users.count %>)</td>
            <% @users.each do |user| %>
              <td class="<%= 'selected' if user.is_attending?(presentation) %>"><%= user.is_attending?(presentation) ? "Y" : "N" %></td>
            <% end %>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
</div>

app/views/users/new.html.erb
<%= render 'fields', user: User.new %>

app/views/users/new.js.erb
$('#registration-form').html("<%= j(render 'fields', user: @user) %>");

app/views/users/success.js.erb
$('#registration-form .modal-body').html('<div class="alert alert-success">Alright, you\'re all set!</div>');
$('#registration-form .modal-footer').remove();
setTimeout(function() {
	$('#registration-form').modal('hide');
}, 2000);